### ISSUE TITLE
Creating an empty submission folder fails

### ISSUE THREAD

**Issue by andrea08** [zerospeech/benchmarks#36]
I installed the package using pip: `pip install zerospeech-benchmarks[all]` with python 3.8 (but I also tried it with python 3.9), and after downloading the dataset when I attempted to create the submission folder, I got the following error:

`AttributeError: 'Namespace' object has no attribute 'quiet'`

The traceback is:
```bash
Traceback (most recent call last):
  File "/home/andrea/miniconda3/envs/zs_abx/bin/zrc", line 8, in <module>
    sys.exit(main())
  File "/home/andrea/miniconda3/envs/zs_abx/lib/python3.8/site-packages/zerospeech/startup.py", line 39, in main
    cli.run()
  File "/home/andrea/miniconda3/envs/zs_abx/lib/python3.8/site-packages/zerospeech/cmd/cli_lib.py", line 258, in run
    cmd.run_cmd(argv=sys.argv[2:])
  File "/home/andrea/miniconda3/envs/zs_abx/lib/python3.8/site-packages/zerospeech/cmd/cli_lib.py", line 91, in run_cmd
    self.run(args)
  File "/home/andrea/miniconda3/envs/zs_abx/lib/python3.8/site-packages/zerospeech/cmd/submission.py", line 43, in run
    benchmark = benchmark_type.benchmark(quiet=argv.quiet)
```

**Comment by nhamilakis** [comment]
Thank you for opening an issue.
The error was mostly a typo, using a bad argument input, i just pushed a fix, it should be up on pypi in a bit.
You have to do `pip install --upgrade zerospeech-benchmarks[all]` to get the updates.
